<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseLocallyBuiltPackage>true</UseLocallyBuiltPackage>
    </PropertyGroup>

    <ItemGroup Condition=" '$(UseLocallyBuiltPackage)' != ''">
        <PackageReference Include="Vogen" Version="999.9.*" />
        <PackageReference Update="MinVer" Version="7.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup Condition=" '$(UseLocallyBuiltPackage)' == ''">
        <PackageReference Include="Vogen" Version="999.9.10219943" />
    </ItemGroup>

</Project>
