<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Vogen</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\strongname.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <Target Name="StampSharedTypesVersion" AfterTargets="MinVer" BeforeTargets="GetAssemblyVersion">
    <PropertyGroup>
      <AssemblyVersion Condition="'$(MinVerMajor)' != ''">$(MinVerMajor).$(MinVerMinor).$(MinVerPatch).0</AssemblyVersion>
      <FileVersion Condition="'$(MinVerMajor)' != ''">$(MinVerMajor).$(MinVerMinor).$(MinVerPatch).0</FileVersion>
      <InformationalVersion Condition="'$(MinVerVersion)' != ''">$(MinVerVersion)</InformationalVersion>
    </PropertyGroup>
  </Target>

  <ItemGroup>
    <PackageReference Update="MinVer" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
