using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Vogen;

internal static class VoFilter
{
    /// <summary>
    /// Returns <c>true</c> when the syntax node is in code that should be skipped by analyzers — i.e.
    /// it is in a source-generator output that is NOT a Razor/Blazor component file.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Two complementary checks identify generated code so both production builds and in-memory test
    /// compilations are handled correctly:
    /// </para>
    /// <list type="number">
    ///   <item>
    ///     <term>File-path check (production / CI)</term>
    ///     <description>
    ///     Source generators emit files whose hint names end in <c>.g.cs</c> / <c>.generated.cs</c>.
    ///     Razor/Blazor files also end in <c>.g.cs</c> but carry <c>.razor</c> or <c>.cshtml</c> in
    ///     the name (e.g. <c>Index.razor.g.cs</c>). Non-Razor <c>.g.cs</c> files — including Vogen's
    ///     own output and third-party generators (EF Core, gRPC, Orleans …) — are skipped immediately.
    ///     </description>
    ///   </item>
    ///   <item>
    ///     <term>Source-text check (test environment / in-memory sources)</term>
    ///     <description>
    ///     In test compilations the Vogen-generated source is added with an auto-assigned path such as
    ///     <c>/0/Test2.cs</c>, so the path check cannot identify it. As a fallback the source text is
    ///     inspected: if the first few lines contain <c>&lt;auto-generated</c> the file is treated as
    ///     generated and skipped. This mirrors the heuristic used by the Roslyn compiler itself.
    ///     Razor-generated files also carry the marker but are already allowed through by the Razor path
    ///     check.
    ///     </description>
    ///   </item>
    /// </list>
    /// </remarks>
    public static bool IsInCodeThatShouldNotBeAnalyzed(SyntaxNode syntaxNode)
    {
        var tree = syntaxNode.SyntaxTree;
        var path = tree.FilePath;

        // Razor/Blazor-generated files MUST always be analysed — they contain user-authored code.
        // Their hint names always contain ".razor" or ".cshtml" (e.g. Index.razor.g.cs).
        bool isRazorOrCshtml =
            !string.IsNullOrEmpty(path) &&
            (path.IndexOf(".razor", System.StringComparison.OrdinalIgnoreCase) >= 0 ||
             path.IndexOf(".cshtml", System.StringComparison.OrdinalIgnoreCase) >= 0);

        if (isRazorOrCshtml) return false;

        // Fast path: non-Razor generator hint-name suffix identifies the file as generated.
        bool isGeneratedByPath =
            !string.IsNullOrEmpty(path) &&
            (path.IndexOf(".g.cs", System.StringComparison.OrdinalIgnoreCase) >= 0 ||
             path.IndexOf(".generated.cs", System.StringComparison.OrdinalIgnoreCase) >= 0);

        if (isGeneratedByPath) return true;

        // Path check inconclusive (test compilations auto-name sources as /0/Test2.cs etc.).
        // Fall back to reading the source text: Vogen and all other source generators prepend
        // a "// <auto-generated>" comment in the first few lines (Roslyn's compiler uses the
        // same heuristic to decide whether a file is generated code).
        return StartsWithAutoGeneratedComment(tree);
    }

    private static bool StartsWithAutoGeneratedComment(SyntaxTree syntaxTree)
    {
        var lines = syntaxTree.GetText().Lines;
        int linesToCheck = lines.Count < 4 ? lines.Count : 4;
        for (int i = 0; i < linesToCheck; i++)
        {
            if (lines[i].ToString().IndexOf("<auto-generated", System.StringComparison.OrdinalIgnoreCase) >= 0)
                return true;
        }

        return false;
    }


    /// <summary>
    /// Tries to get any `ValueObject` attributes specified on the provided symbol.
    /// It might return more than one because the user might have typed more than one.
    /// Even though having more than one is not valid, it's still possible for it to exist,
    /// so we return what is found and let the caller decide what to do.
    /// </summary>
    /// <param name="voSymbolInformation"></param>
    /// <returns></returns>
    public static IEnumerable<AttributeData> TryGetValueObjectAttributes(INamedTypeSymbol voSymbolInformation)
    {
        var attrs = voSymbolInformation.GetAttributes();

        return attrs.Where(a => IsNamedValueObjectAttributeType(a.AttributeClass));
    }

    /// <summary>
    /// Given a type declaration (via the context), it gets the semantic model,
    /// then gets the type declaration, then tries to get any value object
    /// attributes.
    /// </summary>
    /// <param name="context">The context containing the node.</param>
    /// <returns>The target, otherwise null.</returns>
    public static VoTarget? TryGetTarget(GeneratorSyntaxContext context)
    {
        var voSyntaxInformation = (TypeDeclarationSyntax) context.Node;

        var semanticModel = context.SemanticModel;

        if (!HasValueObjectAttributeOnThisSyntax(voSyntaxInformation, semanticModel))
        {
            return null;
        }

        ISymbol declaredSymbol = semanticModel.GetDeclaredSymbol(context.Node)!;

        var voSymbolInformation = (INamedTypeSymbol) declaredSymbol;

        var attributeData = TryGetValueObjectAttributes(voSymbolInformation).ToImmutableArray();

        if (attributeData.Length > 0)
        {
            return new VoTarget(
                semanticModel: semanticModel,
                typeToAugment: voSyntaxInformation,
                nestingInfo: declaredSymbol.ContainingType is not null
                    ? NestingInfo.AsNestedIn(declaredSymbol.ContainingType)
                    : NestingInfo.NotNested,
                symbolForType: voSymbolInformation,
                dataForAttributes: attributeData);
        }

        return null;
    }

    public static bool IsDeclaringATypeAndHasAtLeastOneAttribute(SyntaxNode syntaxNode) =>
        syntaxNode is TypeDeclarationSyntax { AttributeLists.Count: > 0 };

    public static bool IsTarget(INamedTypeSymbol? voClass) =>
        voClass is not null && TryGetValueObjectAttributes(voClass).Any();

    private static bool HasValueObjectAttributeOnThisSyntax(
        TypeDeclarationSyntax typeSyntax,
        SemanticModel semanticModel)
    {
        foreach (var list in typeSyntax.AttributeLists)
        {
            foreach (var attribute in list.Attributes)
            {
                var symbol = semanticModel.GetSymbolInfo(attribute).Symbol as IMethodSymbol;
                var attributeType = symbol?.ContainingType;

                if (IsNamedValueObjectAttributeType(attributeType))
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static bool IsNamedValueObjectAttributeType(INamedTypeSymbol? attributeClass) =>
        attributeClass?.EscapedFullName() == "Vogen.ValueObjectAttribute"
        || attributeClass?.BaseType?.EscapedFullName() == "Vogen.ValueObjectAttribute"
        || attributeClass?.BaseType?.BaseType?.EscapedFullName() == "Vogen.ValueObjectAttribute";
}
