using System;
using System.Linq;
using System.Threading.Tasks;

namespace Vogen.Examples
{
    // ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a source generator named Vogen (https://github.com/SteveDunn/Vogen)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0618
// Suppress warnings for 'Override methods on comparable types'.
#pragma warning disable CA1036
// Suppress Error MA0097 : A class that implements IComparable<T> or IComparable should override comparison operators
#pragma warning disable MA0097
// Suppress warning for 'The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.'
// The generator copies signatures from the BCL, e.g. for `TryParse`, and some of those have nullable annotations.
#pragma warning disable CS8669, CS8632
#pragma warning disable CS8604 // Possible null reference argument.

// Suppress warnings about CS1591: Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable CS1591
namespace MediumTests.SerializationAndConversionTests
{
}
    
    
    class Program
    {
        // ReSharper disable once UnusedParameter.Local
        static async Task Main(string[] args)
        {
            try
            {
                var scenarioTypes = typeof(Program).Assembly.GetTypes()
                    .Where(t => typeof(IScenario).IsAssignableFrom(t) && t != typeof(IScenario)).ToList();

                foreach (var eachScenarioType in scenarioTypes)
                {
                    var instance = (IScenario)Activator.CreateInstance(eachScenarioType)!;
                    WriteBanner(instance);

                    await instance.Run();
                }

                Console.WriteLine("Finished");
            }
            catch (Exception e)
            {
                Console.Error.WriteLine(e);
                Environment.Exit(-1);
            }
        }

        private static void WriteBanner(IScenario scenario)
        {
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine("==========================================================");
            Console.WriteLine($"Running {scenario.GetType().Name}");
            string description = scenario.GetDescription();
            if (!string.IsNullOrEmpty(description))
            {
                Console.Write(description);
                Console.WriteLine("------");

            }
        }
    }
}
