name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v5.4.0
        with:
          dotnet-version: |
            10.0.x
            9.0.x
            8.0.x
            3.1.x
      - uses: actions/cache@v6
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: Build and Test
        run: ./Build.ps1
        shell: pwsh

  run-snapshots:
    name: run-snapshots
    needs: build
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v5.4.0
        with:
          dotnet-version: |
            10.0.x
      - uses: actions/cache@v6
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: Run Snapshots
        run: ./RunSnapshots.ps1
        shell: pwsh

